"""建立可使用 SQL 與 AI Search 的 AI Foundry agent。"""

from foundry_tool_contract import (
    build_execute_sql_tool,
    build_search_documents_tool,
    build_tool_instruction_block,
    get_tool_summary_lines,
)
from foundry_trace import configure_foundry_tracing
from azure.ai.projects.models import PromptAgentDefinition
from azure.ai.projects import AIProjectClient
from azure.identity import DefaultAzureCredential
from load_env import load_all_env
from scenario_utils import (
    build_deployment_name,
    build_scenario_resource_name,
    resolve_data_paths,
    resolve_scenario,
    scenario_resource_suffix,
)
import os
import sys
import json
import argparse


# Parse arguments first
parser = argparse.ArgumentParser()
parser.add_argument("--foundry-only", action="store_true",
                    help="建立只使用 AI Search 的 agent（不使用 Fabric / SQL）")
parser.add_argument("--scenario", default="",
                    help="要使用的情境 key（優先於 DATA_FOLDER）")
parser.add_argument("--data-folder", default="",
                    help="資料資料夾路徑（預設讀取 .env）")
args = parser.parse_args()

FOUNDRY_ONLY = args.foundry_only

# Get script directory for relative paths
script_dir = os.path.dirname(os.path.abspath(__file__))

# Load environment from azd + project .env
load_all_env()


# ============================================================================
# Configuration
# ============================================================================

# Azure services - from azd environment
ENDPOINT = os.getenv("AZURE_AI_PROJECT_ENDPOINT")
MODEL = os.getenv("AZURE_CHAT_MODEL") or os.getenv(
    "MODEL_DEPLOYMENT", "gpt-5.4-mini")
SEARCH_ENDPOINT = os.getenv("AZURE_AI_SEARCH_ENDPOINT")

# Project settings - from .env
if not ENDPOINT:
    print("錯誤：未設定 AZURE_AI_PROJECT_ENDPOINT")
    print("      請先執行 'azd up' 部署 Azure 資源")
    sys.exit(1)

if not SEARCH_ENDPOINT:
    print("錯誤：未設定 AZURE_AI_SEARCH_ENDPOINT")
    print("      請先執行 'azd up' 部署 Azure 資源")
    sys.exit(1)

scenario = resolve_scenario(args.scenario or os.getenv(
    "SCENARIO_KEY") or None, args.data_folder or os.getenv("DATA_FOLDER"), require_capability="search")
paths = resolve_data_paths(scenario)
data_dir = scenario["absoluteDataFolder"]
config_dir = os.fspath(paths["config_dir"])
scenario_suffix = scenario_resource_suffix(scenario["key"])

# ============================================================================
# Load Ontology Config and Schema Prompt
# ============================================================================

# Load ontology config for scenario info
config_path = os.path.join(config_dir, "ontology_config.json")
if not os.path.exists(config_path):
    print("錯誤：找不到 ontology_config.json")
    print("      請先執行 01_generate_sample_data.py")
    sys.exit(1)

with open(config_path) as f:
    ontology_config = json.load(f)

scenario_from_config = ontology_config.get("scenario", "retail")
scenario_name = ontology_config.get("name", "Business Data")
scenario_desc = ontology_config.get("description", "")
tables = list(ontology_config.get("tables", {}).keys())

# Load schema prompt (generated by 04_generate_agent_prompt.py)
prompt_path = os.path.join(config_dir, "schema_prompt.txt")
if os.path.exists(prompt_path):
    with open(prompt_path) as f:
        schema_prompt = f.read()
else:
    schema_prompt = ""
    if not FOUNDRY_ONLY:
        print(
            "警告：找不到 schema_prompt.txt，請先執行 04_generate_agent_prompt.py")

# Load Fabric IDs (optional in foundry-only mode)
fabric_ids_path = os.path.join(config_dir, "fabric_ids.json")
fabric_ids = {}
if os.path.exists(fabric_ids_path):
    with open(fabric_ids_path) as f:
        fabric_ids = json.load(f)
elif not FOUNDRY_ONLY:
    print("錯誤：找不到 fabric_ids.json")
    print("      請先執行 02_create_fabric_items.py，或使用 --foundry-only")
    sys.exit(1)

# Load Search IDs
search_ids_path = os.path.join(config_dir, "search_ids.json")
if os.path.exists(search_ids_path):
    with open(search_ids_path) as f:
        search_ids = json.load(f)
    INDEX_NAME = search_ids.get(
        "index_name", f"{fabric_ids.get('solution_name', 'demo')}-documents")
else:
    fallback_solution_name = fabric_ids.get("solution_name") or build_scenario_resource_name(
        os.getenv("SOLUTION_NAME") or os.getenv(
            "SOLUTION_PREFIX") or os.getenv("AZURE_ENV_NAME", "demo"),
        scenario["key"],
    )
    INDEX_NAME = f"{fallback_solution_name}-documents"
    print(
        f"警告：找不到 search_ids.json，改用預設索引：{INDEX_NAME}")

WORKSPACE_ID = fabric_ids.get("workspace_id")
LAKEHOUSE_NAME = fabric_ids.get("lakehouse_name")
SOLUTION_NAME = fabric_ids.get(
    "solution_name") or build_scenario_resource_name(
        os.getenv("SOLUTION_NAME") or os.getenv(
            "SOLUTION_PREFIX") or os.getenv("AZURE_ENV_NAME", "demo"),
        scenario["key"],
)
agent_role = "search" if FOUNDRY_ONLY else "agent"
AGENT_NAME = build_deployment_name(SOLUTION_NAME, scenario, agent_role)

print(f"\n{'='*60}")
if FOUNDRY_ONLY:
    print("建立 AI Foundry Agent（只用 Search）")
else:
    print("建立 AI Foundry Agent（SQL + Search）")
print(f"{'='*60}")
print(f"Endpoint：{ENDPOINT}")
print(f"模型：{MODEL}")
print(f"Scenario：{scenario['key']}")
print(f"情境：{scenario_name}")
if not FOUNDRY_ONLY:
    print(f"資料表：{', '.join(tables)}")
    print(f"Lakehouse：{LAKEHOUSE_NAME}")
print(f"Search 索引：{INDEX_NAME}")

# ============================================================================
# Build Agent Instructions
# ============================================================================


def build_agent_instructions(config, schema_text, foundry_only=False):
    """Build agent instructions based on mode"""
    scenario_name = config.get("name", "Business Data")
    scenario_desc = config.get("description", "")
    tables_config = config.get("tables", {})
    relationships = config.get("relationships", [])

    table_names = list(tables_config.keys())

    # Build relationship descriptions for JOINs
    join_hints = []
    for rel in relationships:
        from_table = rel.get("from")
        to_table = rel.get("to")
        from_key = rel.get("fromKey")
        to_key = rel.get("toKey")
        join_hints.append(f"{from_table}.{from_key} = {to_table}.{to_key}")

    persona = "樂於協助的助理" if foundry_only else "樂於協助的資料分析助理"
    tool_block = build_tool_instruction_block(
        foundry_only, table_names, schema_text, join_hints)

    return f"""你是一位{persona}，負責回答與 {scenario_name} 相關的問題。

{scenario_desc}

{tool_block}

請保持回答精簡且正確。若查詢失敗，請說明原因並改用其他可行做法。"""


instructions = build_agent_instructions(
    ontology_config, schema_prompt, FOUNDRY_ONLY)
print(f"\n已建立指示內容（{len(instructions)} 字元）")

# ============================================================================
# Tool Definitions
# ============================================================================

# Build tools list based on mode
agent_tools = []

# AI Search Tool (always included)
search_documents_tool = build_search_documents_tool()
agent_tools.append(search_documents_tool)

# SQL Execution Tool (only in full mode)
if not FOUNDRY_ONLY:
    execute_sql_tool = build_execute_sql_tool(tables)
    agent_tools.insert(0, execute_sql_tool)  # SQL first in full mode

# ============================================================================
# Create the Agent
# ============================================================================

print("\n初始化 AI Project Client...")
credential = DefaultAzureCredential()

try:
    project_client = AIProjectClient(
        endpoint=ENDPOINT,
        credential=credential
    )
    print("[OK] AI Project Client 已初始化")
except Exception as e:
    print(f"[FAIL] 初始化 client 失敗：{e}")
    sys.exit(1)

trace_session = configure_foundry_tracing(
    project_client=project_client,
    scenario_name="07_create_foundry_agent",
    service_name="e2e-ms-foundry-workshop.agent-create",
)

if trace_session.enabled:
    print("[OK] 已啟用 Foundry tracing")
elif trace_session.warning:
    print(f"警告：{trace_session.warning}")

try:
    with project_client:
        # Delete existing agent if it exists
        print(f"\n檢查 agent '{AGENT_NAME}' 是否已存在...")
        try:
            with trace_session.span("get-existing-agent"):
                existing_agent = project_client.agents.get(AGENT_NAME)
            if existing_agent:
                print(f"  已找到既有 agent，準備刪除...")
                with trace_session.span("delete-existing-agent"):
                    project_client.agents.delete(AGENT_NAME)
                print(f"[OK] 已刪除既有 agent")
        except Exception:
            print(f"  沒有找到既有 agent")

        # Create agent definition
        tool_desc = "只用 Search" if FOUNDRY_ONLY else "SQL + AI Search"
        print(f"\n正在建立使用 {tool_desc} 工具的 agent...")
        agent_definition = PromptAgentDefinition(
            model=MODEL,
            instructions=instructions,
            tools=agent_tools
        )

        with trace_session.span("create-agent"):
            agent = project_client.agents.create(
                name=AGENT_NAME,
                definition=agent_definition
            )

        print(f"\n[OK] Agent 建立成功！")
        print(f"  Agent ID：{agent.id}")
        print(f"  Agent 名稱：{agent.name}")

except Exception as e:
    print(f"\n[FAIL] 建立 agent 失敗：{e}")
    sys.exit(1)

# ============================================================================
# Save Agent Configuration
# ============================================================================

agent_ids_path = os.path.join(config_dir, "agent_ids.json")
agent_ids = {}
if os.path.exists(agent_ids_path):
    with open(agent_ids_path) as f:
        agent_ids = json.load(f)

# Only save agent-specific info, not environment details
agent_ids["agent_id"] = agent.id
agent_ids["agent_name"] = agent.name
agent_ids["scenario_key"] = scenario["key"]
agent_ids["search_index"] = INDEX_NAME

with open(agent_ids_path, "w") as f:
    json.dump(agent_ids, f, indent=2)

print(f"\n[OK] 已把 Agent 設定寫入：{agent_ids_path}")

# ============================================================================
# Summary
# ============================================================================

if FOUNDRY_ONLY:
    tool_summary = "\n".join(
        f"  {line}" for line in get_tool_summary_lines(True))
    print(f"""
{'='*60}
Search-Only Agent Created Successfully!
{'='*60}

Agent 已建立成功（只用 Search）

Agent ID：{agent.id}
Agent 名稱：{agent.name}
模型：{MODEL}
情境：{scenario_name}

工具：
{tool_summary}

這個 agent 可以回答：
    - 政策、指引、流程
    - 文件內容與常見問答

注意：這個 agent 無法查詢結構化 / 表格資料。
            若要完整功能，請不要加上 --foundry-only。

下一步：
    python scripts/participant_validate_docs.py
""")
else:
    tool_summary = "\n".join(
        f"  {line}" for line in get_tool_summary_lines(False))
    print(f"""
{'='*60}
Multi-Tool AI Foundry Agent Created Successfully!
{'='*60}

多工具 AI Foundry Agent 已建立成功！

Agent ID：{agent.id}
Agent 名稱：{agent.name}
模型：{MODEL}
情境：{scenario_name}

工具：
{tool_summary}

同時會用到兩種工具的範例問題：
    - 「依照我們的免運政策，符合資格的訂單總金額是多少？」
  - "How many orders meet the minimum for loyalty rewards eligibility?"

Next step:
    python scripts/participant_validate_docs_data.py
""")
