"""
07a - Create AI Foundry Agent with SQL + AI Search Tools
Creates an AI Foundry agent that can query both structured data (SQL) and unstructured data (AI Search).

Usage:
    python 07_create_foundry_agent.py              # Full mode (SQL + Search)
    python 07_create_foundry_agent.py --foundry-only  # Search only (no Fabric)

Prerequisites:
    - Run 01_generate_sample_data.py (creates data and ontology_config.json)
    - Run 02_create_fabric_items.py (creates Lakehouse and Ontology) [skip with --foundry-only]
    - Run 03_load_fabric_data.py (loads data to tables) [skip with --foundry-only]
    - Run 04_generate_agent_prompt.py (creates schema_prompt.txt) [skip with --foundry-only]
    - Run 06_upload_to_search.py (uploads PDFs to AI Search)

The agent has function tools:
    Full mode: execute_sql + search_documents
    Foundry-only: search_documents only
"""

from foundry_tool_contract import (
    build_execute_sql_tool,
    build_search_documents_tool,
    build_tool_instruction_block,
    get_tool_summary_lines,
)
from azure.ai.projects.models import PromptAgentDefinition
from azure.ai.projects import AIProjectClient
from azure.identity import DefaultAzureCredential
from load_env import load_all_env
import os
import sys
import json
import argparse

# Parse arguments first
parser = argparse.ArgumentParser()
parser.add_argument("--foundry-only", action="store_true",
                    help="Create agent with AI Search only (no Fabric/SQL)")
args = parser.parse_args()

FOUNDRY_ONLY = args.foundry_only

# Get script directory for relative paths
script_dir = os.path.dirname(os.path.abspath(__file__))

# Load environment from azd + project .env
load_all_env()


# ============================================================================
# Configuration
# ============================================================================

# Azure services - from azd environment
ENDPOINT = os.getenv("AZURE_AI_PROJECT_ENDPOINT")
MODEL = os.getenv("AZURE_CHAT_MODEL") or os.getenv(
    "MODEL_DEPLOYMENT", "gpt-4o-mini")
SEARCH_ENDPOINT = os.getenv("AZURE_AI_SEARCH_ENDPOINT")

# Project settings - from .env
DATA_FOLDER = os.getenv("DATA_FOLDER")

if not ENDPOINT:
    print("ERROR: AZURE_AI_PROJECT_ENDPOINT not set")
    print("       Run 'azd up' to deploy Azure resources")
    sys.exit(1)

if not DATA_FOLDER:
    print("ERROR: DATA_FOLDER not set in .env")
    print("       Run 01_generate_sample_data.py first")
    sys.exit(1)

if not SEARCH_ENDPOINT:
    print("ERROR: AZURE_AI_SEARCH_ENDPOINT not set")
    print("       Run 'azd up' to deploy Azure resources")
    sys.exit(1)

data_dir = os.path.abspath(DATA_FOLDER)

# Set up paths for new folder structure
config_dir = os.path.join(data_dir, "config")
if not os.path.exists(config_dir):
    config_dir = data_dir  # Fallback to old structure

# ============================================================================
# Load Ontology Config and Schema Prompt
# ============================================================================

# Load ontology config for scenario info
config_path = os.path.join(config_dir, "ontology_config.json")
if not os.path.exists(config_path):
    print(f"ERROR: ontology_config.json not found")
    print("       Run 01_generate_sample_data.py first")
    sys.exit(1)

with open(config_path) as f:
    ontology_config = json.load(f)

scenario = ontology_config.get("scenario", "retail")
scenario_name = ontology_config.get("name", "Business Data")
scenario_desc = ontology_config.get("description", "")
tables = list(ontology_config.get("tables", {}).keys())

# Load schema prompt (generated by 04_generate_agent_prompt.py)
prompt_path = os.path.join(config_dir, "schema_prompt.txt")
if os.path.exists(prompt_path):
    with open(prompt_path) as f:
        schema_prompt = f.read()
else:
    schema_prompt = ""
    if not FOUNDRY_ONLY:
        print(
            "WARNING: schema_prompt.txt not found - run 04_generate_agent_prompt.py first")

# Load Fabric IDs (optional in foundry-only mode)
fabric_ids_path = os.path.join(config_dir, "fabric_ids.json")
fabric_ids = {}
if os.path.exists(fabric_ids_path):
    with open(fabric_ids_path) as f:
        fabric_ids = json.load(f)
elif not FOUNDRY_ONLY:
    print(f"ERROR: fabric_ids.json not found")
    print("       Run 02_create_fabric_items.py first, or use --foundry-only")
    sys.exit(1)

# Load Search IDs
search_ids_path = os.path.join(config_dir, "search_ids.json")
if os.path.exists(search_ids_path):
    with open(search_ids_path) as f:
        search_ids = json.load(f)
    INDEX_NAME = search_ids.get(
        "index_name", f"{fabric_ids.get('solution_name', 'demo')}-documents")
else:
    INDEX_NAME = f"{fabric_ids.get('solution_name', 'demo')}-documents"
    print(
        f"WARNING: search_ids.json not found - using default index: {INDEX_NAME}")

WORKSPACE_ID = fabric_ids.get("workspace_id")
LAKEHOUSE_NAME = fabric_ids.get("lakehouse_name")
SOLUTION_NAME = fabric_ids.get(
    "solution_name") or scenario.lower().replace(" ", "-")
# Agent name: simple and consistent
AGENT_NAME = f"{SOLUTION_NAME}-agent"

print(f"\n{'='*60}")
if FOUNDRY_ONLY:
    print("Creating AI Foundry Agent (Search Only)")
else:
    print("Creating AI Foundry Agent (SQL + Search)")
print(f"{'='*60}")
print(f"Endpoint: {ENDPOINT}")
print(f"Model: {MODEL}")
print(f"Scenario: {scenario_name}")
if not FOUNDRY_ONLY:
    print(f"Tables: {', '.join(tables)}")
    print(f"Lakehouse: {LAKEHOUSE_NAME}")
print(f"Search Index: {INDEX_NAME}")

# ============================================================================
# Build Agent Instructions
# ============================================================================


def build_agent_instructions(config, schema_text, foundry_only=False):
    """Build agent instructions based on mode"""
    scenario_name = config.get("name", "Business Data")
    scenario_desc = config.get("description", "")
    tables_config = config.get("tables", {})
    relationships = config.get("relationships", [])

    table_names = list(tables_config.keys())

    # Build relationship descriptions for JOINs
    join_hints = []
    for rel in relationships:
        from_table = rel.get("from")
        to_table = rel.get("to")
        from_key = rel.get("fromKey")
        to_key = rel.get("toKey")
        join_hints.append(f"{from_table}.{from_key} = {to_table}.{to_key}")

    persona = "helpful assistant" if foundry_only else "helpful data analyst assistant"
    tool_block = build_tool_instruction_block(
        foundry_only, table_names, schema_text, join_hints)

    return f"""You are a {persona} that answers questions about {scenario_name}.

{scenario_desc}

{tool_block}

Be concise and accurate. If a query fails, explain the issue and try a different approach."""


instructions = build_agent_instructions(
    ontology_config, schema_prompt, FOUNDRY_ONLY)
print(f"\nBuilt instructions ({len(instructions)} chars)")

# ============================================================================
# Tool Definitions
# ============================================================================

# Build tools list based on mode
agent_tools = []

# AI Search Tool (always included)
search_documents_tool = build_search_documents_tool()
agent_tools.append(search_documents_tool)

# SQL Execution Tool (only in full mode)
if not FOUNDRY_ONLY:
    execute_sql_tool = build_execute_sql_tool(tables)
    agent_tools.insert(0, execute_sql_tool)  # SQL first in full mode

# ============================================================================
# Create the Agent
# ============================================================================

print("\nInitializing AI Project Client...")
credential = DefaultAzureCredential()

try:
    project_client = AIProjectClient(
        endpoint=ENDPOINT,
        credential=credential
    )
    print("[OK] AI Project Client initialized")
except Exception as e:
    print(f"[FAIL] Failed to initialize client: {e}")
    sys.exit(1)

try:
    with project_client:
        # Delete existing agent if it exists
        print(f"\nChecking if agent '{AGENT_NAME}' already exists...")
        try:
            existing_agent = project_client.agents.get(AGENT_NAME)
            if existing_agent:
                print(f"  Found existing agent, deleting...")
                project_client.agents.delete(AGENT_NAME)
                print(f"[OK] Deleted existing agent")
        except Exception:
            print(f"  No existing agent found")

        # Create agent definition
        tool_desc = "Search only" if FOUNDRY_ONLY else "SQL + AI Search"
        print(f"\nCreating agent with {tool_desc} tools...")
        agent_definition = PromptAgentDefinition(
            model=MODEL,
            instructions=instructions,
            tools=agent_tools
        )

        agent = project_client.agents.create(
            name=AGENT_NAME,
            definition=agent_definition
        )

        print(f"\n[OK] Agent created successfully!")
        print(f"  Agent ID: {agent.id}")
        print(f"  Agent Name: {agent.name}")

except Exception as e:
    print(f"\n[FAIL] Failed to create agent: {e}")
    sys.exit(1)

# ============================================================================
# Save Agent Configuration
# ============================================================================

agent_ids_path = os.path.join(config_dir, "agent_ids.json")
agent_ids = {}
if os.path.exists(agent_ids_path):
    with open(agent_ids_path) as f:
        agent_ids = json.load(f)

# Only save agent-specific info, not environment details
agent_ids["agent_id"] = agent.id
agent_ids["agent_name"] = agent.name
agent_ids["search_index"] = INDEX_NAME

with open(agent_ids_path, "w") as f:
    json.dump(agent_ids, f, indent=2)

print(f"\n[OK] Agent config saved to: {agent_ids_path}")

# ============================================================================
# Summary
# ============================================================================

if FOUNDRY_ONLY:
    tool_summary = "\n".join(
        f"  {line}" for line in get_tool_summary_lines(True))
    print(f"""
{'='*60}
Search-Only Agent Created Successfully!
{'='*60}

Agent ID: {agent.id}
Agent Name: {agent.name}
Model: {MODEL}
Scenario: {scenario_name}

Tools:
{tool_summary}

This agent can answer questions about:
  - Policies, guidelines, procedures
  - Document content and FAQs

Note: This agent CANNOT query structured/tabular data.
      For full functionality, run without --foundry-only flag.

Next step:
  python scripts/08_test_foundry_agent.py --foundry-only
""")
else:
    tool_summary = "\n".join(
        f"  {line}" for line in get_tool_summary_lines(False))
    print(f"""
{'='*60}
Multi-Tool AI Foundry Agent Created Successfully!
{'='*60}

Agent ID: {agent.id}
Agent Name: {agent.name}
Model: {MODEL}
Scenario: {scenario_name}

Tools:
{tool_summary}

Sample questions that use BOTH tools:
  - "What's the total value of orders that qualify for free shipping based on our policy?"
  - "How many orders meet the minimum for loyalty rewards eligibility?"

Next step:
  python scripts/08_test_foundry_agent.py
""")
